name: Update oc.docs

on:
  repository_dispatch:
    types: dispatch-from-docs
  push:
    branches:
      - main
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:

    runs-on: self-hosted

    steps:
      - name: Clone sources
        run: |
          rm -rf ..?* .[!.]* *
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" clone --recurse-submodules  "https://github.com/abcdesktopio/oc.docs.git" .
          git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" submodule update --init --recursive --remote
          ls -la
          ls -la docs
   
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: oc.docs
          push: true
          tags: |
            abcdesktopio/oc.docs
